### ISSUE TITLE
Change to relay hooks

### ISSUE THREAD

**Issue by youngkidwarrior** [ShenaniganDApp/shenanigan-monorepo#15]
Relay has a hooks API here

https://github.com/relay-tools/relay-hooks

- [ ] Refactor Comment List to use relay-hooks usePagination hook #18 
- [ ] Refactor ProfilePage component to the useQuery hook #19
- [ ] Refactor CreateCommentMutation to use relay hooks #20
