### ISSUE TITLE
Challenge Diamond Contracts

### ISSUE THREAD

**Issue by youngkidwarrior** [ShenaniganDApp/shenanigan-monorepo#53]
First read [Diamond Contract Motivation](https://eips.ethereum.org/EIPS/eip-2535#motivation)

Here is the structure of a Diamond Contract 
![image](https://user-images.githubusercontent.com/36084652/97768394-faa3cc80-1adf-11eb-9af5-8ad4b8314966.png)

__Issues:__
- [ ] #54 Implement Diamond Standard
- [ ] #55  Transition Challenges.sol to Challenge Facet Contract
- [ ] #57 Transition Challenge Mediator, AMB Mediator, ChallengeRegistry, and SignatureChecker contracts to facets. 
- [ ] #56 Write the full Challenge Diamond [example](https://github.com/mudgen/diamond-3/blob/master/contracts/Diamond.sol)
